---
all:
  children:
    kubernetes_cluster:
      children:
        masters:
          hosts:
            cluster-raspi-1.cluster.lan:
              kubernetes_role: master
        workers:
          hosts:
            cluster-raspi-[2:5].cluster.lan:
              kubernetes_role: node
