---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-test-nfs-pvc-rwx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
